### PR TITLE
Add login dialog to prompt user to enter labrad credentials

### PR DESCRIPTION
**Pull request by maffoo**
Also refactored main app so that UI lives in a custom element, rather than in an autobound template in index.html, so that we can treat it more like all the other custom elements we have.

When testing, be sure to restart both the scala and node dev servers, as some server APIs have changed.

### CODE REVIEW

**Comment by joshm-3b6b58** [comment]
How do I log out? I closed my chrome browser completely (I think) but when I went to localhost:3000 I wasn't prompted to re-enter my password.

**Comment by maffoo** [comment]
Good point; I should add that :) Right now the credentials are stored in localStorage, which essentially lasts forever. I could store them in sessionStorage instead (in which case they'd go away when you close the browser window), and/or have an option to explicitly log out.

**Comment by joshm-3b6b58** [comment]
I think the lasts forever but with the option to log out is best for now.

**Comment by maffoo** [comment]
@joshmutus, did you take a look at the latest changes? I could make the "Remember password" option default to true, or just remove it altogether. Let me know what you think.

**Comment by joshm-3b6b58** [comment]
I never use remember password features since I forget my passwords if I
don't enter them constantly. I would just keep it as it is defaulted to
false.

The logout button is very easy to see :)

**Comment by joshm-3b6b58** [comment]
Otherwise LGTM

**Pull request merged**
