### PR TITLE
Allow ENTER in login dialog

### LINKED ISSUE #95: Pressing ENTER after typing the password doesn't work
You have to click the `login` button. Hitting enter sends you back to where you started.

### PR DESCRIPTION
**Pull request by maffoo**
Fixes #95

### CODE REVIEW

**Comment by DanielSank** [comment]
Hey @maffoo, I'm thinking how best to test stuff like this. Can we set up a server to run the site so that folks to connect and see if it works on their system (i.e. various browsers)?

**Comment by joshm-3b6b58** [comment]
I think we should place a heavy emphasis one just using Chrome for this...

**Comment by DanielSank** [comment]
Tested to work. Lemme look at the code real quick.

**Comment by DanielSank** [comment]
Hmm, I don't think I can review this. What does `app.$` mean?

**Comment by maffoo** [comment]
The `.$` attribute is an object whose attributes refer to DOM nodes with explicit id attributes inside a custom element. This is something that polymer creates on elements defined through polymer. In this case, `app` is a `labrad-app` element, so `app.$.loginForm` selects the form with that id defined in `labrad-app.html`, etc.

**Comment by DanielSank** [comment]
Definitely punting to @joshmutus on this one. I just don't know enough.

**Comment by joshm-3b6b58** [comment]
LGTM

**Pull request closed without merging**
