### PR TITLE
Add modal dialog notification for copy and delete in progress

### PR DESCRIPTION
**Pull request by joshm-3b6b58**
A little notification on the bottom right of the screen will pop up when an operation is in progress. This says "working..." The notification will be dismissed once the operation is complete. 

Notification will autodismiss after 60s.

This is only implemented for things that take a long time like copying and deleting folders. 

Fixes https://github.com/labrad/scalabrad-web/issues/55

### CODE REVIEW

**Comment by DanielSank** [comment]
> Notification will autodismiss after 60s.

Why?

**Comment by joshm-3b6b58** [comment]
@DanielSank: In chatting with @maffoo the toast notification probably isn't right since the call to the manager on that context blocks any other interaction with GUI from happening. I'll make this a modal dialog and push a new commit. Sec.

**Comment by joshm-3b6b58** [comment]
@DanielSank take a look whenever and tell me what you think.

**Comment by joshm-3b6b58** [comment]
@maffoo do you mind taking a look at this and letting me know if you have any thoughts?

**Comment by maffoo** [comment]
@joshmutus, I think it would be nice to indicate what operation is in progress (as opposed to just "working..."). Also, it would be good to change the `toastText` id since this element is now a dialog.

**Comment by joshm-3b6b58** [comment]
Will do

**Comment by joshm-3b6b58** [comment]
@maffoo LMK if this looks ok? I kind of forgot about it :/

**Comment by maffoo** [comment]
LGTM

**Pull request merged**
