### PR TITLE
Cleanup and reorganize server api code

### PR DESCRIPTION
**Pull request by maffoo**
The goal here is to clean up the server code and isolate the dependencies on play as much as follows. To that end, I've removed the dependencies on akka in jsonrpc so that it just uses scala futures and plain old locking to protect the mutable data in JsonRpcTransport. In the server itself, I've cleaned up the api code and removed the play imports, and consolidated the play code into just one single controller class.

### CODE REVIEW

**Comment by maffoo** [comment]
bump

**Comment by joshm-3b6b58** [comment]
Yeah, sorry. I've been distracted by a cleanroom issue. This falls under
the category of "it's a lot of scala code that I'm not so sure what to look
for"

**Comment by DanielSank** [comment]
Yeah, @maffoo this one is going to be hard just because we're not familiar with all the libraries.

**Comment by maffoo** [comment]
Well, do you think I should just go ahead with this change, or do you guys want to take some time to understand the code and/or just check out the branch and run it?

I will say that most of what's going on here is moving files around and changing how some constructor parameters get passed. These changes are all in the category of "if it compiles, then it's good". The one thing that's a bit more involved is the change to JsonRpcTransport; I removed the dependence on akka actors so this would be usable with other websocket libraries, and pulled all the actor stuff into the play controller itself (since play uses actors for web sockets). Let me know what you guys want to do.

**Comment by joshm-3b6b58** [comment]
So I switched to this branch and compiled and ran the servers, the app isn't rendering for me immediately:

```
[info] Compiling 1 Scala source to /usr/local/google/home/mutus/programming/scalabrad-web/jsonrpc/target/scala-2.11/classes...
[info] Compiling 1 Scala source to /usr/local/google/home/mutus/programming/scalabrad-web/jsonrpc/target/scala-2.11/classes...
[info] Compiling 16 Scala sources and 2 Java sources to /usr/local/google/home/mutus/programming/scalabrad-web/server/target/scala-2.11/classes...

--- (RELOAD) ---

11:07:53.148 [application-akka.actor.default-dispatcher-845] INFO  p.a.l.concurrent.ActorSystemProvider - Shutdown application default Akka system: application
11:07:53.404 [application-akka.actor.default-dispatcher-845] WARN  application - Logger configuration in conf files is deprecated and has no effect. Use a logback configuration file instead.
11:07:53.472 [application-akka.actor.default-dispatcher-845] INFO  p.a.l.concurrent.ActorSystemProvider - Starting application default Akka system: application
11:07:53.596 [application-akka.actor.default-dispatcher-845] INFO  play.api.Play$ - Application started (Dev)
11:07:53.644 [application-akka.actor.default-dispatcher-2] INFO  org.labrad.browser.LabradConnection - connected
11:07:53.647 [application-akka.actor.default-dispatcher-4] INFO  org.labrad.browser.LabradConnection - connected
got message: {"jsonrpc":"2.0","id":0,"method":"org.labrad.registry.dir","params":{"path":[]}}
got message: {"jsonrpc":"2.0","id":0,"method":"org.labrad.registry.dir","params":{"path":[]}}
sending: {"jsonrpc":"2.0","id":0,"error":{"code":-32601,"message":"Method not found","data":{"method":"org.labrad.registry.dir"}}}
sending: {"jsonrpc":"2.0","id":0,"error":{"code":-32601,"message":"Method not found","data":{"method":"org.labrad.registry.dir"}}}
got message: {"jsonrpc":"2.0","id":1,"method":"org.labrad.datavault.dir","params":[[]]}
sending: {"jsonrpc":"2.0","id":1,"error":{"code":-32601,"message":"Method not found","data":{"method":"org.labrad.datavault.dir"}}}
11:12:44.490 [application-akka.actor.default-dispatcher-3] INFO  org.labrad.browser.LabradConnection - disconnected.  will reconnect in 10 seconds
11:12:44.987 [application-akka.actor.default-dispatcher-3] INFO  org.labrad.browser.LabradConnection - connected
got message: {"jsonrpc":"2.0","id":0,"method":"org.labrad.datavault.dir","params":[[]]}
sending: {"jsonrpc":"2.0","id":0,"error":{"code":-32601,"message":"Method not found","data":{"method":"org.labrad.datavault.dir"}}}
11:12:54.542 [application-akka.actor.default-dispatcher-8] INFO  org.labrad.browser.LabradConnection - disconnected.  will reconnect in 10 seconds
11:12:55.104 [application-akka.actor.default-dispatcher-8] INFO  org.labrad.browser.LabradConnection - connected
got message: {"jsonrpc":"2.0","id":0,"method":"org.labrad.datavault.dir","params":[[]]}
sending: {"jsonrpc":"2.0","id":0,"error":{"code":-32601,"message":"Method not found","data":{"method":"org.labrad.datavault.dir"}}}
got message: {"jsonrpc":"2.0","id":1,"method":"org.labrad.manager.connections","params":[]}
sending: {"jsonrpc":"2.0","id":1,"error":{"code":-32601,"message":"Method not found","data":{"method":"org.labrad.manager.connections"}}}
11:12:56.904 [application-akka.actor.default-dispatcher-3] INFO  org.labrad.browser.LabradConnection - disconnected.  will reconnect in 10 seconds
11:12:57.397 [application-akka.actor.default-dispatcher-3] INFO  org.labrad.browser.LabradConnection - connected
got message: {"jsonrpc":"2.0","id":0,"method":"org.labrad.manager.connections","params":[]}
sending: {"jsonrpc":"2.0","id":0,"error":{"code":-32601,"message":"Method not found","data":{"method":"org.labrad.manager.connections"}}}
```

**Comment by maffoo** [comment]
looks like you don't have a labrad manager running?

**Comment by joshm-3b6b58** [comment]
I definitely have a labrad manager running as everything was working before I switched branches. Maybe I crashed ?Let me check

**Comment by maffoo** [comment]
oh wait, nvm. that's probably just reloading the page

**Comment by maffoo** [comment]
can you try running 'clean' before starting the server?

**Comment by joshm-3b6b58** [comment]
sbt clean?

**Comment by maffoo** [comment]
ok, I'm seeing the same issue here too. Sorry, thought I checked this before. I'll get things fixed.

**Comment by joshm-3b6b58** [comment]
I ran sbt clean then `sbt client/compile server/run` and it crashes with this traceback: 

```
mutus@mutus:~/programming/scalabrad-web$ sbt client/compile server/run
[info] Loading project definition from /usr/local/google/home/mutus/programming/scalabrad-web/project/project
[info] Loading project definition from /usr/local/google/home/mutus/programming/scalabrad-web/project
[info] Set current project to scalabrad-web (in build file:/usr/local/google/home/mutus/programming/scalabrad-web/)
[error] Expected ID character
[error] Not a valid command: client (similar: eclipse, plugin, set)
[error] Expected project ID
[error] Expected configuration
[error] Expected ':' (if selecting a configuration)
[error] Expected key
[error] Not a valid key: client (similar: clean, lintian, licenses)
[error] client/compile
[error]       ^
```

**Comment by joshm-3b6b58** [comment]
OK cool. Ping me when you want me to check it out on my end.

**Comment by maffoo** [comment]
All right, I think that was a false alarm. After a clean things work fine for me. As for the error you're seeing, there is no more client project because we stripped out the GWT code. You can just run `sbt clean server/run`. (Dan and I updated the readme to reflect this)

**Comment by joshm-3b6b58** [comment]
Oh that makes sense. I was just pressing up arrow in the terminal :/

**Comment by joshm-3b6b58** [comment]
Still not working on my end. Same error as before

**Comment by joshm-3b6b58** [comment]
complete output: 

```
$ sbt clean server/run
[info] Loading project definition from /usr/local/google/home/mutus/programming/scalabrad-web/project/project
[info] Loading project definition from /usr/local/google/home/mutus/programming/scalabrad-web/project
[info] Set current project to scalabrad-web (in build file:/usr/local/google/home/mutus/programming/scalabrad-web/)
[success] Total time: 0 s, completed Aug 4, 2015 11:31:23 AM
[info] Updating {file:/usr/local/google/home/mutus/programming/scalabrad-web/}jsonrpc...
[info] Resolving jline#jline;2.12.1 ...
[info] Done updating.
[info] Updating {file:/usr/local/google/home/mutus/programming/scalabrad-web/}server...
[info] Resolving jline#jline;2.12.1 ...
[info] downloading https://repo1.maven.org/maven2/com/typesafe/play/play-server_2.11/2.4.2/play-server_2.11-2.4.2.jar ...
[info]  [SUCCESSFUL ] com.typesafe.play#play-server_2.11;2.4.2!play-server_2.11.jar (667ms)
[info] downloading https://repo1.maven.org/maven2/com/typesafe/play/play-netty-server_2.11/2.4.2/play-netty-server_2.11-2.4.2.jar ...
[info]  [SUCCESSFUL ] com.typesafe.play#play-netty-server_2.11;2.4.2!play-netty-server_2.11.jar (379ms)
[info] downloading http://jcenter.bintray.com/org/labrad/scalabrad_2.11/0.3.1/scalabrad_2.11-0.3.1.jar ...
[info]  [SUCCESSFUL ] org.labrad#scalabrad_2.11;0.3.1!scalabrad_2.11.jar (2543ms)
[info] downloading https://repo1.maven.org/maven2/com/typesafe/play/play_2.11/2.4.2/play_2.11-2.4.2.jar ...
[info]  [SUCCESSFUL ] com.typesafe.play#play_2.11;2.4.2!play_2.11.jar (1570ms)
[info] downloading https://repo1.maven.org/maven2/com/typesafe/play/play-iteratees_2.11/2.4.2/play-iteratees_2.11-2.4.2.jar ...
[info]  [SUCCESSFUL ] com.typesafe.play#play-iteratees_2.11;2.4.2!play-iteratees_2.11.jar (422ms)
[info] downloading https://repo1.maven.org/maven2/com/typesafe/play/play-json_2.11/2.4.2/play-json_2.11-2.4.2.jar ...
[info]  [SUCCESSFUL ] com.typesafe.play#play-json_2.11;2.4.2!play-json_2.11.jar (372ms)
[info] downloading https://repo1.maven.org/maven2/com/typesafe/play/play-netty-utils/2.4.2/play-netty-utils-2.4.2.jar ...
[info]  [SUCCESSFUL ] com.typesafe.play#play-netty-utils;2.4.2!play-netty-utils.jar (217ms)
[info] downloading https://repo1.maven.org/maven2/joda-time/joda-time/2.8.1/joda-time-2.8.1.jar ...
[info]  [SUCCESSFUL ] joda-time#joda-time;2.8.1!joda-time.jar (360ms)
[info] downloading https://repo1.maven.org/maven2/com/typesafe/play/play-functional_2.11/2.4.2/play-functional_2.11-2.4.2.jar ...
[info]  [SUCCESSFUL ] com.typesafe.play#play-functional_2.11;2.4.2!play-functional_2.11.jar (344ms)
[info] downloading https://repo1.maven.org/maven2/com/typesafe/play/play-datacommons_2.11/2.4.2/play-datacommons_2.11-2.4.2.jar ...
[info]  [SUCCESSFUL ] com.typesafe.play#play-datacommons_2.11;2.4.2!play-datacommons_2.11.jar (223ms)
[info] downloading https://repo1.maven.org/maven2/com/typesafe/play/play-test_2.11/2.4.2/play-test_2.11-2.4.2.jar ...
[info]  [SUCCESSFUL ] com.typesafe.play#play-test_2.11;2.4.2!play-test_2.11.jar (269ms)
[info] downloading https://repo1.maven.org/maven2/com/typesafe/play/play-omnidoc_2.11/2.4.2/play-omnidoc_2.11-2.4.2.jar ...
[info]  [SUCCESSFUL ] com.typesafe.play#play-omnidoc_2.11;2.4.2!play-omnidoc_2.11.jar (3204ms)
[info] downloading https://repo1.maven.org/maven2/com/typesafe/play/play-docs_2.11/2.4.2/play-docs_2.11-2.4.2.jar ...
[info]  [SUCCESSFUL ] com.typesafe.play#play-docs_2.11;2.4.2!play-docs_2.11.jar (2752ms)
[info] Done updating.
[info] Compiling 4 Scala sources and 2 Java sources to /usr/local/google/home/mutus/programming/scalabrad-web/jsonrpc/target/scala-2.11/classes...
[info] 'compiler-interface' not yet compiled for Scala 2.11.7. Compiling...
[info]   Compilation completed in 13.557 s

--- (Running the application, auto-reloading is enabled) ---

[info] p.a.l.c.ActorSystemProvider - Starting application default Akka system: application
[info] p.c.s.NettyServer - Listening for HTTP on /0:0:0:0:0:0:0:0:9000

(Server started, use Ctrl+D to stop and go back to the console...)

[info] Compiling 16 Scala sources and 2 Java sources to /usr/local/google/home/mutus/programming/scalabrad-web/server/target/scala-2.11/classes...
11:32:34.854 [ForkJoinPool-1-worker-9] WARN  application - Logger configuration in conf files is deprecated and has no effect. Use a logback configuration file instead.
11:32:35.433 [ForkJoinPool-1-worker-9] INFO  p.a.l.concurrent.ActorSystemProvider - Starting application default Akka system: application
11:32:35.585 [ForkJoinPool-1-worker-9] INFO  play.api.Play - Application started (Dev)
11:32:36.000 [application-akka.actor.default-dispatcher-3] INFO  org.labrad.browser.LabradConnection - connected
got message: {"jsonrpc":"2.0","id":0,"method":"org.labrad.registry.dir","params":{"path":[]}}
sending: {"jsonrpc":"2.0","id":0,"error":{"code":-32601,"message":"Method not found","data":{"method":"org.labrad.registry.dir"}}}
11:32:40.960 [application-akka.actor.default-dispatcher-2] INFO  org.labrad.browser.LabradConnection - connected
got message: {"jsonrpc":"2.0","id":0,"method":"org.labrad.registry.dir","params":{"path":[]}}
sending: {"jsonrpc":"2.0","id":0,"error":{"code":-32601,"message":"Method not found","data":{"method":"org.labrad.registry.dir"}}}
got message: {"jsonrpc":"2.0","id":1,"method":"org.labrad.registry.dir","params":{"path":[]}}
sending: {"jsonrpc":"2.0","id":1,"error":{"code":-32601,"message":"Method not found","data":{"method":"org.labrad.registry.dir"}}}
11:32:43.529 [application-akka.actor.default-dispatcher-2] INFO  org.labrad.browser.LabradConnection - disconnected.  will reconnect in 10 seconds
11:32:44.078 [application-akka.actor.default-dispatcher-3] INFO  org.labrad.browser.LabradConnection - connected
got message: {"jsonrpc":"2.0","id":0,"method":"org.labrad.registry.dir","params":{"path":[]}}
sending: {"jsonrpc":"2.0","id":0,"error":{"code":-32601,"message":"Method not found","data":{"method":"org.labrad.registry.dir"}}}
```

**Comment by maffoo** [comment]
can you just try ctrl+D and then run the server again (without cleaning)?

**Comment by maffoo** [comment]
It looks like the problem here is related to compilation order. If you force ApiBackend.scala to be compiled after the other files (either by editing after compiling the rest of the app, or by renaming it to be something like ZApiBackend.scala), then things work. Ugh...

Previously we got lucky because the code that analyzed the jsonrpc api classes was in WebsocketController.scala, which comes alphabetically after the other classes, but when that was moved into ApiBackend.scala this issue popped up.

**Comment by maffoo** [comment]
Ok guys, I just added a commit that changes the way the jsonrpc macro stuff works so it no longer needs annotations. I like this a lot better, and it removes the weirdness around compilation order that the annotations were causing. Now instead of the jsonrpc method names being added as annotations on the callable methods, we instead define a "routing table" that maps the jsonrpc method names to methods on local objects. This is similar to how play does things with its routes file, but we use a macro instead of code generation. It also means that the api classes themselves do not need to know anything whatsoever about jsonrpc, which is nice.

The changes are mostly just removing annotations from api classes and adding the routing tables in ApiBackend.scala, so I'd suggest looking at those. The diff in JsonRpc.scala is pretty big, but I would suggest if you want to look at it that you just look at the final file (https://github.com/labrad/scalabrad-web/blob/60fec4797949653abe47a99a5ca670bcda7707c4/jsonrpc/src/main/scala/org/labrad/browser/jsonrpc/JsonRpc.scala) rather than the diff, because I don't that was code either of you was very familiar with anyway. I've tried to actually comment things in that file to make it more clear what's going on. In particular, the comments on JsonRpc.routes and JsonRpc.proxy describe the route format.

I've tested on my machine that this works from a clean compilation and that the jsonrpc works, but please do check this out for yourself.

**Comment by DanielSank** [comment]
> This is similar to how play does things with its routes file, but we use a macro instead of code generation.

Perhaps play could be improved in this way...

> It also means that the api classes themselves do not need to know anything whatsoever about jsonrpc, which is nice.

w00t! That's really cool.

**Comment by maffoo** [comment]
@DanielSank, yes, I've been wanting to write a routing layer like this for http for a long time, and I think it could be a really useful thing for making little web services in scala. Now that we've got a version that works for jsonrpc, it'd be super easy to modify for http. The one other big thing that play's routing library gives you is reverse routing. I haven't figured out how this approach could work with reverse routing, but for most things that I've wanted to do, reverse routing is not really all that important.

**Comment by joshm-3b6b58** [comment]
Compiles and runs on my machine, so I guess LGTM?

**Pull request merged**
