### PR TITLE
Edit registry values in dialog box instead of inline.

### LINKED ISSUE #60: Registry editor doesn't work, provides no feedback.
When I modify a registry value, it shows up as changed, when I navigate to a different folder and back, the change disappears.

### PR DESCRIPTION
**Pull request by maffoo**
This is much simpler than the inline editing due to the modal interface and generally it just works (does not rely on so many quirks of polymer element behavior). If we have time in the future to tweak and test, we can revisit the inline editing.

Fixes #60 and #61.

### CODE REVIEW

**Comment by joshm-3b6b58** [comment]
I'm a little bummed we're going away from the inline editing. Hopefully we can circle back and fix it. 

Also there's a bug where if I have a first key selected, then click on a second key, the dialog opens prompting me to edit the first key.

**Comment by maffoo** [comment]
@joshmutus, I'm unable to reproduce the issue you mentioned. If I select key 'A' and then click on the value for key 'B', the dialog shows me the value of 'B' to edit. Any other repro instructions?

One thing that might be happening is that after trying to figure out the problem @DanielSank was having with not being able to edit at all, I blew away and reinstalled all my bower components. It's possible there's some difference in our bower packages that is causing issues here too.

**Comment by maffoo** [comment]
Also, re: direct editing, I also think it'd be nice to resurrect it; one of these days when we have the time to get it right.

**Comment by maffoo** [comment]
@joshmutus, when you get a chance, can you try again? Fixed up the way data binding was working and it no relies on selection to pick the right key name.

**Comment by joshm-3b6b58** [comment]
Cool, bug fixed. On my end it brings up the dialog on single click. It would be nice to make this on double click so we can select without editing keys.

**Comment by joshm-3b6b58** [comment]
LGTM

**Pull request merged**
