### PR TITLE
Updated 1D plots to be easier to read.

### PR DESCRIPTION
**Pull request by adamcw**
Fixes issue #145 by updating the 1D plots in grapher to use the same default colors as Google Charts as well as increasing the stroke width to 1.5 (up from 1.0).

### CODE REVIEW

**Comment by adamcw** [comment]
I'm not sure that these colors are that visually appealing, we may want to consider a future enhancement to allow swapping between a color-blind and non-color-blind mode. People spend a lot of time looking at graphs, we don't want them to be ugly.

**Comment by joshm-3b6b58** [comment]
Yeah these colours... 

Can we just use the Google chart colors? https://developers.google.com/chart/

**Comment by adamcw** [comment]
I have changed the colors to the Google chart colors. They all start looking rather the same after six or so, clearly a pallet chosen for bar/pie chart graphics where you only need neighbors to be differentiated.

**Comment by joshm-3b6b58** [comment]
Beyond six traces it's a little hard to draw any conclusion anyways, so I wouldn't worry about it. I like this scheme, we can always add more shades or whatever if people complain. 

@maffoo how many colors did the delphi grapher have anyways?

This LGTM

**Comment by jwenner** [comment]
The Delphi grapher has 6: blue, red, green, cyan, purple, brown

**Pull request merged**
